name: osr

dependencies:
    - python=3.7.13
    - pip=21.2.2
    - pytorch::pytorch=1.12.0 py3.7_cuda11.3_cudnn8.3.2_0
    - metric-learning::pytorch-metric-learning=1.5.1 pyh39e3cac_0
    - conda-forge::ray-tune=1.12.1 py37h89c1867_0
    - conda-forge::albumentations=1.2.1 pyhd8ed1ab_0
    - conda-forge::tensorboard=2.9.1 pyhd8ed1ab_0
    - torchvision=0.13.0
    - pycocotools=2.0.4
    - notebook=6.4.12
    - matplotlib=3.5.2
    - pandas=1.3.5
