# Dataset
dataset: 'prw'
dataset_dir: '/datasets/prw'
train_set: 'trainval'
test_set: 'test'
retrieval_name_list: ('test',)

# OIM
oim_cq_size: 500

# Model
model: 'convnext'
backbone_arch: 'convnext_base'

# GFN
gfn_mode: 'combined'
gfn_query_mode: 'oim'
gfn_scene_pool_size: 56

# Optimization
epochs: 30
batch_size: 8

# Augmentation
aug_mode:
    - 'rrc'
    - 'rrc2'
aug_crop_res: 512
aug_rfc_prob: 1.0
aug_rsc_prob:
    - 0.0
    - 1.0

# Logging
trial_name: 'prw_ablation_augmentation_rfc-rrc'
eval_interval: 30
ckpt_interval: 30
log_dir: './logging'
