# Dataset
dataset: 'cuhk'
dataset_dir: '/datasets/cuhk'
train_set: 'trainval'
test_set: 'test'
retrieval_name_list: ('G100',)

# OIM
oim_cq_size: 5000

# Model
model: 'convnext'
backbone_arch: 'convnext_base'

# GFN
gfn_mode: 'combined'
gfn_query_mode: 'batch'
gfn_scene_pool_size: 56

# Optimization
epochs: 30
batch_size: 8

# Augmentation
aug_mode: 'rrc2'
aug_crop_res: 640

# Logging
trial_name: 'cuhk_final'
eval_interval: 30
ckpt_interval: 30
log_dir: './logging'
